---

- include_tasks: nw_requirements_rhui.yml
- include_tasks: nw_requirements_rhua.yml
  when:
    - in('rhua', group_names)

- include_tasks: nw_requirements_cds.yml
  when:
    - in('cds', group_names)

- include_tasks: nw_requirements_gluster.yml
  when:
    - in('gluster', group_names)
