---

- include: nw_requirements_rhui.yml
- include: nw_requirements_rhua.yml
  when:
    - 'rhua' in group_names

- include: nw_requirements_cds.yml
  when:
    - 'cds' in group_names

- include: nw_requirements_gluster.yml
  when:
    - 'gluster' in group_names
