---
- name: Check if the required port is open by the firewall configuration
  assert:
    that:
      - "{{ nmap_scan_ports.stdout | regex_search(gluster_required_ports | join(' .*'), multiline=True) }}"

# vim:sw=2:ts=2:et:
