---

- include_tasks: nw_requirements_of_rhui.yml
- include_tasks: nw_requirements_of_rhua.yml
  when:
    - "{{ 'rhua' in group_names }}"

- include_tasks: nw_requirements_of_cds.yml
  when:
    - "{{ 'cds' in group_names }}"

- include_tasks: nw_requirements_of_gluster.yml
  when:
    - "{{ 'gluster' in group_names }}"
