---
- name: Ensure Gluster volume mounted read-only
  mount:
    src: "{{ rhui_storage_gluster_brick_dir }}"
    path: "{{ rhui_storage_gluster_volume_mnt }}"
    fstype: none
    opts: ro,bind
    state: mounted

# vim:sw=2:ts=2:et:
